#!/usr/bin/env node
/**
 * Pull public repositories from GitHub and write src/data/repos.json.
 *
 *   GITHUB_USER=yourname node scripts/fetch-github.mjs
 *
 * Only repositories carrying the topic in GITHUB_TOPIC (default "website")
 * are listed. That means you curate the page from GitHub itself: add the
 * topic to a repo and it appears in the next refresh, with no site edit.
 *
 * Repositories owned by someone else (a survey or collaboration account) can
 * be listed explicitly in EXTRA_REPOS below.
 *
 * A token is optional. Without one you get 60 requests/hour, which is plenty;
 * in CI, GITHUB_TOKEN raises it to 5000 and is provided automatically.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const OUT = join(ROOT, 'src/data/repos.json');
const OVERRIDES = join(ROOT, 'src/data/overrides.json');

const USER = process.env.GITHUB_USER ?? 'mifumagalli';
const TOPIC = process.env.GITHUB_TOPIC ?? 'website';
const TOKEN = process.env.GITHUB_TOKEN;

/** "owner/repo" entries to include regardless of who owns them. */
const EXTRA_REPOS = [];

const headers = {
  Accept: 'application/vnd.github+json',
  'X-GitHub-Api-Version': '2022-11-28',
  'User-Agent': 'michelefumagalli.com-build',
  ...(TOKEN ? { Authorization: `Bearer ${TOKEN}` } : {}),
};

async function gh(path) {
  const res = await fetch(`https://api.github.com${path}`, { headers });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`GitHub returned ${res.status} for ${path}\n${body.slice(0, 300)}`);
  }
  return res.json();
}

function normalise(r) {
  return {
    name: r.full_name,
    description: r.description ?? null,
    url: r.html_url,
    homepage: r.homepage || null,
    language: r.language ?? null,
    stars: r.stargazers_count ?? 0,
    pushedAt: (r.pushed_at ?? '').slice(0, 10),
    topics: (r.topics ?? []).filter((t) => t !== TOPIC).sort(),
  };
}

async function main() {
  const owned = [];
  for (let p = 1; p <= 5; p++) {
    const batch = await gh(`/users/${USER}/repos?per_page=100&page=${p}&sort=pushed&type=owner`);
    owned.push(...batch);
    if (batch.length < 100) break;
  }

  const tagged = owned.filter(
    (r) => !r.fork && !r.archived && !r.private && (r.topics ?? []).includes(TOPIC)
  );

  const extra = [];
  for (const slug of EXTRA_REPOS) {
    try {
      extra.push(await gh(`/repos/${slug}`));
    } catch (err) {
      console.warn(`  skipped ${slug}: ${err.message.split('\n')[0]}`);
    }
  }

  let overrides = { repoNotes: {} };
  try {
    overrides = JSON.parse(await readFile(OVERRIDES, 'utf8'));
  } catch {
    /* optional */
  }
  const notes = overrides.repoNotes ?? {};

  const repos = [...tagged, ...extra]
    .map(normalise)
    .map((r) => ({ ...r, note: notes[r.name] ?? notes[r.name.split('/')[1]] ?? null }))
    .sort((a, b) => b.pushedAt.localeCompare(a.pushedAt));

  // Ignore star counts and push dates when deciding whether anything changed,
  // so a month in which nothing was published produces no pull request.
  const signature = (list) =>
    JSON.stringify(list.map((r) => [r.name, r.description, r.language, r.homepage, r.note]));

  let previous = null;
  try {
    previous = JSON.parse(await readFile(OUT, 'utf8'));
  } catch {
    /* first run */
  }

  if (previous && signature(previous.repos ?? []) === signature(repos)) {
    console.log(`No change: ${repos.length} repositories tagged "${TOPIC}".`);
    return;
  }

  const payload = {
    _note: `Generated by scripts/fetch-github.mjs. Add the "${TOPIC}" topic to a repository to list it here.`,
    generated: new Date().toISOString().slice(0, 10),
    user: USER,
    topic: TOPIC,
    count: repos.length,
    repos,
  };

  await writeFile(OUT, JSON.stringify(payload, null, 2) + '\n', 'utf8');
  console.log(`Wrote ${repos.length} repositories to src/data/repos.json`);
}

main().catch((err) => {
  console.error('GitHub fetch failed:', err.message);
  process.exit(1);
});
