#!/usr/bin/env node
/**
 * Keep GitHub metadata current for the resources that reference a repository.
 *
 *   node scripts/fetch-github.mjs
 *
 * This does NOT decide what appears on the site. The site's Data & Code page
 * is driven entirely by the files in src/content/resources/ — this script
 * reads the `github: owner/repo` field out of those files and refreshes the
 * few fields that go stale on their own (language, last push, stars).
 *
 * Items hosted on Bitbucket, Zenodo or an institutional archive simply have
 * no `github` field, and are untouched by this.
 *
 * A token is optional. Without one you get 60 requests/hour, which is plenty;
 * in CI, GITHUB_TOKEN raises it to 5000 and is provided automatically.
 */

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const RESOURCES = join(ROOT, 'src/content/resources');
const OUT = join(ROOT, 'src/data/repos.json');

const TOKEN = process.env.GITHUB_TOKEN;

const headers = {
  Accept: 'application/vnd.github+json',
  'X-GitHub-Api-Version': '2022-11-28',
  'User-Agent': 'michelefumagalli.com-build',
  ...(TOKEN ? { Authorization: `Bearer ${TOKEN}` } : {}),
};

/** Pull every `github: owner/repo` out of the resource frontmatter. */
async function collectSlugs() {
  let files = [];
  try {
    files = (await readdir(RESOURCES)).filter((f) => /\.mdx?$/.test(f));
  } catch {
    console.log('No src/content/resources directory yet — nothing to do.');
    return [];
  }

  const slugs = new Set();
  for (const f of files) {
    const text = await readFile(join(RESOURCES, f), 'utf8');
    const m = /^github:\s*['"]?([\w.-]+\/[\w.-]+)['"]?\s*$/m.exec(text);
    if (m) slugs.add(m[1]);
  }
  return [...slugs].sort();
}

async function fetchRepo(slug) {
  const res = await fetch(`https://api.github.com/repos/${slug}`, { headers });
  if (!res.ok) {
    throw new Error(`${res.status} ${res.statusText}`);
  }
  const r = await res.json();
  return {
    description: r.description ?? null,
    language: r.language ?? null,
    stars: r.stargazers_count ?? 0,
    pushedAt: (r.pushed_at ?? '').slice(0, 10),
    homepage: r.homepage || null,
    url: r.html_url,
  };
}

async function main() {
  const slugs = await collectSlugs();

  if (slugs.length === 0) {
    console.log('No resources reference a GitHub repository — nothing to fetch.');
    return;
  }

  const repos = {};
  for (const slug of slugs) {
    try {
      repos[slug] = await fetchRepo(slug);
      console.log(`  ok  ${slug}`);
    } catch (err) {
      // A renamed or private repo shouldn't fail the whole run; the page
      // still renders from the hand-written entry, just without metadata.
      console.warn(`  skip ${slug}: ${err.message}`);
    }
  }

  // Stars and push dates change on their own; only rewrite the file when
  // something a reader would notice has changed, so a quiet month opens no
  // pull request.
  const signature = (r) =>
    JSON.stringify(
      Object.entries(r)
        .sort()
        .map(([k, v]) => [k, v.description, v.language, v.homepage])
    );

  let previous = null;
  try {
    previous = JSON.parse(await readFile(OUT, 'utf8'));
  } catch {
    /* first run */
  }

  if (previous && signature(previous.repos ?? {}) === signature(repos)) {
    console.log(`No change: ${Object.keys(repos).length} repositories.`);
    return;
  }

  const payload = {
    _note:
      'Generated by scripts/fetch-github.mjs from the `github:` fields in src/content/resources/. Do not edit by hand.',
    generated: new Date().toISOString().slice(0, 10),
    count: Object.keys(repos).length,
    repos,
  };

  await writeFile(OUT, JSON.stringify(payload, null, 2) + '\n', 'utf8');
  console.log(`Wrote metadata for ${Object.keys(repos).length} repositories.`);
}

main().catch((err) => {
  console.error('GitHub fetch failed:', err.message);
  process.exit(1);
});
